// AUTO-GENERATED by scripts/generate-build-info.mjs — do not edit by hand.
// This committed placeholder is overwritten at build time (prebuild-docs hook).
export const BUILD_INFO = {
  timestamp: '',
};
